### ISSUE TITLE
Nuitka compiler error

### ISSUE THREAD

**Issue by fuuddanni** [rabbitstack/fibratus#1]
When compiling with nuitka a get an error (What sould i do?): Thxs for reply:

E:\Python27\libs/libpython27.a(dmmes01026.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'

E:\Python27\libs/libpython27.a(dmmes00712.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'

E:\Python27\libs/libpython27.a(dmmes00245.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'

E:\Python27\libs/libpython27.a(dmmes00236.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'

E:\Python27\libs/libpython27.a(dmmes00648.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'

E:\Python27\libs/libpython27.a(dmmes00343.o):(.idata$7+0x0): more undefined references to `_head_C__build27_cpython_PCBuild_libpython27_a' follow

collect2: ld returned 1 exit status

g++: unrecognized option '-static-libstdc++'

**Comment by rabbitstack** [comment]
Can you post the full nuitka command invocation? Please make sure you meet the following requirements:

- C++ compiler (ships with Visual Studio)
- Python 2.7 (required by nuitka)
- Python 3.4 (required by fibratus)

**Comment by fuuddanni** [comment]
Thxs for your answer. I´m compiling as following: nuitka --recurse-all
--standalone --output-dir=E:\Github\Fibratus\fibratus\compile --verbose
cli.py > compilererror.txt

gcc --version: gcc (GCC) 4.4.7 20111023 (prerelease) [svn/rev.180339 -
mingw-w64/oz]
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
(Think it is included in [Home Page](http://wiki.github.com/bmatzelle/gow/)
| Ligthweight cygwin)


But i don´t have Python3.4 installed on system. Can you recommend some best
practice installing python3.4 parallel to 2.7?


2016-05-26 10:51 GMT+02:00 Nedim Šabić <notifications@github.com>:

**Comment by rabbitstack** [comment]
I would try to compile using the Visual C++ compiler (comes with Visual Studio 2012+). I often use a separate MSI installer for every Python version, and that works for me. You can try with pyenv too.
https://github.com/yyuu/pyenv

**Comment by rabbitstack** [comment]
Shipping Fibratus with portable installlers [here](https://github.com/rabbitstack/fibratus/releases).

**Comment by fuuddanni** [comment]
Thank you, but the portable installer also doesn´t work for me.

2016-05-28 20:54 GMT+02:00 Nedim Šabić <notifications@github.com>:

**Comment by rabbitstack** [comment]
Can you provide more details about the error? Which version of Windows are you running?

**Comment by fuuddanni** [comment]
Yes for sure:
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
<OSVersionInformation>
<WindowsNTVersion>6.1</WindowsNTVersion>
<Build>7601 Service Pack 1</Build>
<Product>(0x1): Windows 7 Ultimate</Product>
<Edition>Ultimate</Edition>
<BuildString>7601.23418.amd64fre.win7sp1_ldr.160408-2045</BuildString>
<Revision>1130</Revision>
<Flavor>Multiprocessor Free</Flavor>
<Architecture>X64</Architecture>
<LCID>1031</LCID>
</OSVersionInformation>
<ParentProcessInformation>
<ParentProcessId>4368</ParentProcessId>
<ParentProcessPath>C:\Windows\explorer.exe</ParentProcessPath>
<ParentProcessCmdLine>C:\Windows\Explorer.EXE</ParentProcessCmdLine>
</ParentProcessInformation>
<ProblemSignatures>
<EventType>APPCRASH</EventType>
<Parameter0>fibratus.exe</Parameter0>
<Parameter1>0.0.0.0</Parameter1>
<Parameter2>5749a806</Parameter2>
<Parameter3>python34.dll</Parameter3>
<Parameter4>3.4.3150.1013</Parameter4>
<Parameter5>54ecf0c8</Parameter5>
<Parameter6>c0000005</Parameter6>
<Parameter7>0000000000102854</Parameter7>
</ProblemSignatures>
<DynamicSignatures>
<Parameter1>6.1.7601.2.1.0.256.1</Parameter1>
<Parameter2>1031</Parameter2>
<Parameter22>8026</Parameter22>
<Parameter23>80262724487bae400e6e580a1315696c</Parameter23>
<Parameter24>b35e</Parameter24>
<Parameter25>b35e3c9419b4e92e7efe936b710916f2</Parameter25>
</DynamicSignatures>
<SystemInformation>
<MID>76915B81-2FB5-4B66-939B-28151B66D162</MID>
<SystemManufacturer>MSI</SystemManufacturer>
<SystemProductName>MS-7758</SystemProductName>
<BIOSVersion>V2.13B3</BIOSVersion>
</SystemInformation>
</WERReportMetadata>

AND:
<?xml version="1.0" encoding="UTF-16"?>
<DATABASE>
<EXE NAME="fibratus.exe" FILTER="CMI_FILTER_PRIVACY">
    <MATCHING_FILE NAME="fibratus.exe" SIZE="14084096"
CHECKSUM="0x8B5F52FA" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0"
LINKER_VERSION="0x0" LINK_DATE="05/28/2016 14:15:34"
UPTO_LINK_DATE="05/28/2016 14:15:34" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="msvcr100.dll" SIZE="829264" CHECKSUM="0x29AB8F17"
BIN_FILE_VERSION="10.0.40219.325" BIN_PRODUCT_VERSION="10.0.40219.325"
PRODUCT_VERSION="10.00.40219.325" FILE_DESCRIPTION="Microsoft® C Runtime
Library" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft®
Visual Studio® 2010" FILE_VERSION="10.00.40219.325"
ORIGINAL_FILENAME="msvcr100_clr0400.dll"
INTERNAL_NAME="msvcr100_clr0400.dll" LEGAL_COPYRIGHT="© Microsoft
Corporation.  All rights reserved." VERDATEHI="0x0" VERDATELO="0x0"
VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32"
PE_CHECKSUM="0xD8A41" LINKER_VERSION="0xA0000"
UPTO_BIN_FILE_VERSION="10.0.40219.325"
UPTO_BIN_PRODUCT_VERSION="10.0.40219.325" LINK_DATE="06/11/2011 00:54:04"
UPTO_LINK_DATE="06/11/2011 00:54:04" EXPORT_NAME="MSVCR100.dll"
VER_LANGUAGE="Englisch (USA) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="msvcrt.dll" SIZE="634880" CHECKSUM="0x4B3C4996"
BIN_FILE_VERSION="7.0.7601.17744" BIN_PRODUCT_VERSION="6.1.8638.17744"
PRODUCT_VERSION="7.0.7601.17744" FILE_DESCRIPTION="Windows NT CRT DLL"
COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows®
Operating System" FILE_VERSION="7.0.7601.17744 (win7sp1_gdr.111215-1535)"
ORIGINAL_FILENAME="msvcrt.dll" INTERNAL_NAME="msvcrt.dll"
LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved."
VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x1"
MODULE_TYPE="WIN32" PE_CHECKSUM="0xA708A" LINKER_VERSION="0x60001"
UPTO_BIN_FILE_VERSION="7.0.7601.17744"
UPTO_BIN_PRODUCT_VERSION="6.1.8638.17744" LINK_DATE="12/16/2011 08:37:19"
UPTO_LINK_DATE="12/16/2011 08:37:19" EXPORT_NAME="msvcrt.dll"
VER_LANGUAGE="Englisch (USA) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="python34.dll" SIZE="4057600" CHECKSUM="0x48D7EA22"
BIN_FILE_VERSION="3.4.3150.1013" BIN_PRODUCT_VERSION="3.4.3150.1013"
PRODUCT_VERSION="3.4.3" FILE_DESCRIPTION="Python Core" COMPANY_NAME="Python
Software Foundation" PRODUCT_NAME="Python" FILE_VERSION="3.4.3"
ORIGINAL_FILENAME="python34.dll" INTERNAL_NAME="Python DLL"
LEGAL_COPYRIGHT="Copyright © 2001-2015 Python Software Foundation.
Copyright © 2000 BeOpen.com. Copyright © 1995-2001 CNRI. Copyright ©
1991-1995 SMC." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004"
VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x3E563C"
LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="3.4.3150.1013"
UPTO_BIN_PRODUCT_VERSION="3.4.3150.1013" LINK_DATE="02/24/2015 21:44:40"
UPTO_LINK_DATE="02/24/2015 21:44:40" EXPORT_NAME="python34.dll"
VER_LANGUAGE="Sprachneutral [0x0]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="tdh.dll" SIZE="859648" CHECKSUM="0xB026694A"
BIN_FILE_VERSION="6.1.7601.18247" BIN_PRODUCT_VERSION="6.1.7601.18247"
PRODUCT_VERSION="6.1.7601.18247" FILE_DESCRIPTION="Event Trace Helper
Library" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft®
Windows® Operating System" FILE_VERSION="6.1.7601.18247
(win7sp1_gdr.130828-1532)" ORIGINAL_FILENAME="tdh.dll"
INTERNAL_NAME="tdh.dll" LEGAL_COPYRIGHT="© Microsoft Corporation. All
rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004"
VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0xDB48F"
LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.18247"
UPTO_BIN_PRODUCT_VERSION="6.1.7601.18247" LINK_DATE="08/29/2013 02:16:41"
UPTO_LINK_DATE="08/29/2013 02:16:41" EXPORT_NAME="tdh.dll"
VER_LANGUAGE="Englisch (USA) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="ucrtbase.dll" SIZE="961192" CHECKSUM="0xB7003B4E"
BIN_FILE_VERSION="10.0.10137.0" BIN_PRODUCT_VERSION="10.0.10137.0"
PRODUCT_VERSION="10.0.10137.0" FILE_DESCRIPTION="Microsoft® C Runtime
Library" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft®
Windows® Operating System" FILE_VERSION="10.0.10137.0 (th1.150602-2238)"
ORIGINAL_FILENAME="ucrtbase.dll" INTERNAL_NAME="ucrtbase.dll"
LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved."
VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2"
MODULE_TYPE="WIN32" PE_CHECKSUM="0xF8B5E" LINKER_VERSION="0xA0000"
UPTO_BIN_FILE_VERSION="10.0.10137.0"
UPTO_BIN_PRODUCT_VERSION="10.0.10137.0" LINK_DATE="06/03/2015 09:29:02"
UPTO_LINK_DATE="06/03/2015 09:29:02" EXPORT_NAME="ucrtbase.dll"
VER_LANGUAGE="Englisch (USA) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="vcruntime140.dll" SIZE="88752"
CHECKSUM="0x662D3F65" BIN_FILE_VERSION="14.0.23026.0"
BIN_PRODUCT_VERSION="14.0.23026.0" PRODUCT_VERSION="14.00.23026.0"
FILE_DESCRIPTION="Microsoft® C Runtime Library" COMPANY_NAME="Microsoft
Corporation" PRODUCT_NAME="Microsoft® Visual Studio® 2015"
FILE_VERSION="14.00.23026.0 built by: WCSETUP"
ORIGINAL_FILENAME="vcruntime140.dll" INTERNAL_NAME="vcruntime140.dll"
LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved."
VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2"
MODULE_TYPE="WIN32" PE_CHECKSUM="0x1B312" LINKER_VERSION="0xA0000"
UPTO_BIN_FILE_VERSION="14.0.23026.0"
UPTO_BIN_PRODUCT_VERSION="14.0.23026.0" LINK_DATE="06/26/2015 05:28:31"
UPTO_LINK_DATE="06/26/2015 05:28:31" EXPORT_NAME="VCRUNTIME140.dll"
VER_LANGUAGE="Englisch (USA) [0x409]" EXE_WRAPPER="0x0" />
</EXE>
<EXE NAME="python34.dll" FILTER="CMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="python34.dll" SIZE="4057600" CHECKSUM="0x48D7EA22"
BIN_FILE_VERSION="3.4.3150.1013" BIN_PRODUCT_VERSION="3.4.3150.1013"
PRODUCT_VERSION="3.4.3" FILE_DESCRIPTION="Python Core" COMPANY_NAME="Python
Software Foundation" PRODUCT_NAME="Python" FILE_VERSION="3.4.3"
ORIGINAL_FILENAME="python34.dll" INTERNAL_NAME="Python DLL"
LEGAL_COPYRIGHT="Copyright © 2001-2015 Python Software Foundation.
Copyright © 2000 BeOpen.com. Copyright © 1995-2001 CNRI. Copyright ©
1991-1995 SMC." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004"
VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x3E563C"
LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="3.4.3150.1013"
UPTO_BIN_PRODUCT_VERSION="3.4.3150.1013" LINK_DATE="02/24/2015 21:44:40"
UPTO_LINK_DATE="02/24/2015 21:44:40" EXPORT_NAME="python34.dll"
VER_LANGUAGE="Sprachneutral [0x0]" EXE_WRAPPER="0x0" />
</EXE>
<EXE NAME="kernel32.dll" FILTER="CMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="kernel32.dll" SIZE="1163264" CHECKSUM="0xADFC88B8"
BIN_FILE_VERSION="6.1.7601.23418" BIN_PRODUCT_VERSION="6.1.7601.23418"
PRODUCT_VERSION="6.1.7601.18015" FILE_DESCRIPTION="Client-DLL für Windows
NT-Basis-API" COMPANY_NAME="Microsoft Corporation"
PRODUCT_NAME="Betriebssystem Microsoft® Windows®"
FILE_VERSION="6.1.7601.18015 (win7sp1_gdr.121129-1432)"
ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="©
Microsoft Corporation. Alle Rechte vorbehalten." VERDATEHI="0x0"
VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32"
PE_CHECKSUM="0x122E58" LINKER_VERSION="0x60001"
UPTO_BIN_FILE_VERSION="6.1.7601.23418"
UPTO_BIN_PRODUCT_VERSION="6.1.7601.23418" LINK_DATE="04/09/2016 07:00:43"
UPTO_LINK_DATE="04/09/2016 07:00:43" EXPORT_NAME="KERNEL32.dll"
VER_LANGUAGE="Deutsch (Deutschland) [0x407]" EXE_WRAPPER="0x0" />
</EXE>
</DATABASE>

Here are my specs:
Betriebssystemname:                            Microsoft Windows 7 Ultimate
Betriebssystemversion:                         6.1.7601 Service Pack 1
Build 7601
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                Eigenständige Arbeitsstation
Betriebssystem-Buildtyp:                       Multiprocessor Free
Systemhersteller:                                   MSI
Systemmodell:                                       MS-7758
Systemtyp:                                             x64-based PC
Prozessor(en):                                      1 Prozessor(en)
installiert.
                                                               [01]:
Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~2788 MHz
BIOS-Version:                                        American Megatrends
Inc. V2.13B3, 11.06.2012
Gesamter physikalischer Speicher:      16.338 MB


C:\Users\Besitzer>set
ALLUSERSPROFILE=C:\ProgramData
AMDAPPSDKROOT=C:\Program Files (x86)\AMD APP\
ANDROID_NDK_PATH=C:\Users\Besitzer\Documents\Android\ndk\android-ndk-r10e
APPDATA=C:\Users\Besitzer\AppData\Roaming
BONJOUR_SDK_HOME=E:\Bonjour SDK\
CLASSPATH=E:\Java8\jdk\bin\tools.jar;
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=WATSON
ComSpec=C:\Windows\system32\cmd.exe
ConEmuANSI=ON
ConEmuAnsiLog=
ConEmuArgs=
ConEmuBackHWND=0x000203A0
ConEmuBaseDir=E:\PentestBox\PentestBox\vendor\conemu-maximus5\ConEmu
ConEmuBuild=140707
ConEmuConfig=
ConEmuDir=E:\PentestBox\PentestBox\vendor\conemu-maximus5
ConEmuDrawHWND=0x00020364
ConEmuDrive=E:
ConEmuHooks=Enabled
ConEmuHWND=0x0006026C
ConEmuPID=5304
ConEmuServerPID=7672
ConEmuWorkDir=C:\Users\Besitzer
ConEmuWorkDrive=C:
Corona SDK=E:\Corona SDK\Corona Simulator.exe
Devmgr_show_nonpresent_devices=1
EDITOR=~/AppData/Roaming/GitPad/GitPad.exe
FP_NO_HOST_CHECK=NO
GOROOT=E:\Go\
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HAXEPATH=E:\HaxeToolkit\haxe\
HOMEDRIVE=C:
HOMEPATH=\Users\Besitzer
JAVA_HOME=E:\Java8\jdk\lib
LOCALAPPDATA=C:\Users\Besitzer\AppData\Local
LOGONSERVER=\\WATSON
MOZ_PLUGIN_PATH=E:\SumatraPDF\
NEKO_INSTPATH=E:\HaxeToolkit\neko
NUMBER_OF_PROCESSORS=8
OS=Windows_NT
Path=E:\PentestBox\PentestBox\vendor\conemu-maximus5\ConEmu;E:\PentestBox\PentestBox\vendor\conemu-maximus5;E:\Python27\;E:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;E:\PythonPackages\Qt5\Lib\site-packages\PyQt5;C:\Program
Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD
APP\bin\x86;C:\Program Files (x86)\Nmap\;C:\Program Files
(x86)\Java\jre7\bin\;C:\Windows\System32\;C:\Windows;C:\Program Files
(x86)\ATI Technologies\ATI.ACE\Core-Static;E:\Schneider
Electric\Vijeo-WebGate
Control\;E:\Python2.7;E:\Synedra\ViewPersonal;E:\AMD\02022014\ATI.ACE\Core-Static;E:\Python2.7\Scripts\;E:\Calibre2\;C:\Program
Files\Samsung\AllShare Framework DMS\1.3.23\;C:\Program
Files\Samsung\AllShare Framework DMS\1.3.23\64bit\;C:\Program Files
(x86)\Paragon Software\Paragon ExtFS for
Windows;E:\Perl\perl\bin;E:\Perl\perl\site\bin;E:\Perl\c\bin;E:\Ruby193\DevKit;E:\xampp\php;E:\HaxeToolkit\haxe\;E:\HaxeToolkit\neko;E:\nodejs\;E:\Gow\bin;E:\Go\bin;C:\Python27\;C:\Python27\Lib;C:\Program
Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program
Files\Git\cmd;C:\Program Files (x86)\GtkSharp\2.12\bin;E:\010 Hex
Editor;C:\WINDOWS\system32\WindowsPowerShell\v1.0;;E:\Github\Fibratus\Fibratus\Execute\bin;E:\Github\Fibratus\Fibratus\Execute\bin;E:\Fibratus\bin;E:\Ruby193\bin;C:\Program
Files
(x86)\Java\jre7\bin\java.exe;E:\Ruby193\DevKit;C:\Users\Besitzer\AppData\Roaming\npm;C:\Users\Besitzer\AppData\Local\.meteor\;E:\Go;E:\Go\bin\;E:\Ncrack;E:\Ncrack
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3a09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SSLKEYLOGFILE=E:\SSLKEYLOG\sslkeylog.log
SYNEDRA_HOME=E:\Synedra\
synedra_ViewPersonal_HOME=E:\Synedra\ViewPersonal
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\Besitzer\AppData\Local\Temp
TMP=C:\Users\Besitzer\AppData\Local\Temp
USERDOMAIN=Watson
USERNAME=Besitzer
USERPROFILE=C:\Users\Besitzer
VBOX_MSI_INSTALL_PATH=E:\VitrualBox\
VS140COMNTOOLS=E:\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

I don´t know what is going wrong.

2016-05-29 7:42 GMT+02:00 Nedim Šabić <notifications@github.com>:

**Comment by rabbitstack** [comment]
Did you try setting the `PYTHONIOENCODING` enviornment variable? Launch a console and issue:
`set PYTHONIOENCODING=UTF-8` and then `fibratus`.

**Comment by fuuddanni** [comment]
Have tried now set PYTHONIOENCODING=UTF-8 but doesn´t work.

2016-05-29 8:41 GMT+02:00 Nedim Šabić <notifications@github.com>:

**Comment by rabbitstack** [comment]
Do you see any exception on the console or it just crashes?

**Comment by fuuddanni** [comment]
[image: Inline-Bild 1]  i only see the crash without exception.

Eventlog shows following:
Fehlerbucket 224637142, Typ 28
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: fibratus.exe
P2: 0.0.0.0
P3: 5749a806
P4: python34.dll
P5: 3.4.3150.1013
P6: 54ecf0c8
P7: c0000005
P8: 0000000000102854
P9:
P10:

Angefügte Dateien:
C:\Users\Besitzer\AppData\Local\Temp\WER9FAB.tmp.WERInternalMetadata.xml
C:\Users\Besitzer\AppData\Local\Temp\WERB722.tmp.appcompat.txt
C:\Users\Besitzer\AppData\Local\Temp\WERB732.tmp.mdmp

Diese Dateien befinden sich möglicherweise hier:
C:\Users\Besitzer\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_fibratus.exe_bf45fc36bcf3053fe2024dbfae6aff9dc1_140befdc

Analysesymbol:
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 7bbafbf2-2576-11e6-a9ca-005056c00008
Berichtstatus: 9

AND

Name der fehlerhaften Anwendung: fibratus.exe, Version: 0.0.0.0,
Zeitstempel: 0x5749a806
Name des fehlerhaften Moduls: python34.dll, Version: 3.4.3150.1013,
Zeitstempel: 0x54ecf0c8
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000102854
ID des fehlerhaften Prozesses: 0xbc4
Startzeit der fehlerhaften Anwendung: 0x01d1b9833d8b4ccd
Pfad der fehlerhaften Anwendung: E:\Fibratus\Fibratus\bin\fibratus.exe
Pfad des fehlerhaften Moduls: E:\Fibratus\Fibratus\bin\python34.dll
Berichtskennung: 7bbafbf2-2576-11e6-a9ca-005056c00008



2016-05-29 10:24 GMT+02:00 Nedim Šabić <notifications@github.com>:

**Comment by rabbitstack** [comment]
Well, this is really weird. I'm not sure if installing fibratus to a non standard location could  cause the crash. If im not wrong you installed it to `E:\Fibratus\Fibratus`, and it should be `Program files\Rabbitstack\Fibratus`.

**Comment by fuuddanni** [comment]
I´m getting the same error by reinstalling into default path of ssd c:\

[image: Inline-Bild 1]

2016-05-29 10:44 GMT+02:00 Nedim Šabić <notifications@github.com>:

**Comment by rabbitstack** [comment]
I've just installed it on my laptop with Windows 7 virtual machine, and I wasn't able to reproduce the problem. It all works as expected.

**Comment by fuuddanni** [comment]
I just reinstalled python version 3.4 and then fibratus again. Program
seems to be executed but nothing happens at the command line (i use
conemu).

E:\Fibratus\bin>fibratus.exe -h
Usage:
    fibratus run ([--filament=<filament>] | [--filters <kevents>...])
    fibratus list-kevents
    fibratus list-filaments
    fibratus -h | --help
    fibratus --version

Options:
    -h --help                 Show this screen.
    --filament=<filament>     Specify the filament to execute.
    --version                 Show version.

E:\Fibratus\bin>fibratus.exe run
Starting fibratus...

2016-05-29 11:17 GMT+02:00 Nedim Šabić <notifications@github.com>:

**Comment by rabbitstack** [comment]
I'm not 100% sure, but that could be because of fibratus trying to query the system handle of type named pipe. `NtQueryObject` function hangs  indefinitely and it blocks the main thread. I'll look into this to be fixed in the next release.
