### ISSUE TITLE
Issue with connection.py in multiprocess module

### ISSUE THREAD

**Issue by zorga** [rabbitstack/fibratus#10]
Hi !

I've installed everything to make Fibratus work in an 64 bits Windows 7 environment with Python3.4

Anyway, when I try "fibratus run" I get the following error, for which I've found zero documentation:

ImportError : Cannot import name 'WAIT_ABANDONED_0' (from the _winapi lib)

Do you have an idea about how to solve that issue ?

Thanks a lot for your work !

**Comment by rabbitstack** [comment]
Can you confirm there is the  `multiprocess` Cython extension in your `site-packages` directory? (should be in $PYTHON_HOME\Lib\site-packages\_multiprocess.pyd)

**Comment by zorga** [comment]
Yes I confirm I have it. Sorry I should have mentioned that.

**Comment by rabbitstack** [comment]
@zorga can you paste the output of the `pip list` command? This is really a weird issue. You can also try this installation steps:

1. Download and install the Python 3.4 distribution.
2. Download Visual Studio and install Visual C++. Make sure to export the `VS100COMNTOOLS` environment variable so it points to `%VS140COMNTOOLS%`.
3. Install Cython. `pip install Cython`
4. Finally, install Fibratus. `pip install fibratus`

**Comment by zorga** [comment]
Hello

Thank you for your response. I've "solved" the problem by hard-coding the value of WAIT_ABANDONED_0 in the connection.py file. It will be all right for what I need right now.

Anyway, yes, I have Python3.4, Visual C++ via VSE2010, and Cython. And here's the output of the pip list command for my environment, just in case.

C:\Users\fibratus>python -m pip list
anyconfig (0.6.0)
APScheduler (3.0.5)
Cython (0.23.4)
dill (0.2.5)
docopt (0.6.2)
elasticsearch (5.0.0)
fibratus (0.4.1)
Logbook (0.12.5)
multiprocess (0.70.4)
pika (0.10.0)
pip (1.5.4)
PTable (0.9.2)
pyaml (15.8.2)
pyreadline (2.1)
pytz (2016.10)
PyYAML (3.12)
setuptools (2.1)
six (1.10.0)
tzlocal (1.3)
urllib3 (1.19.1)

**Comment by rabbitstack** [comment]
Hi @zorga

I'm glad you found a workaround. From the output of the `pip list` it all looks ok. Not sure if the compiler version could make a difference. I recommend visual c 2012+

**Comment by rabbitstack** [comment]
@zorga. I wasn't able to reproduce this issue. Could we close it?

**Comment by zorga** [comment]
Hello @rabbitstack yes we can close it. Thanks for your consideration anyway :)
