### ISSUE TITLE
Fibratus stuck enumerating system handles

### ISSUE THREAD

**Issue by emmanueltsukerman** [rabbitstack/fibratus#12]
![fibratus](https://cloud.githubusercontent.com/assets/23566736/22408816/849cc804-e634-11e6-9433-e6f388905b66.png)

**Comment by rabbitstack** [comment]
@emmanueltsukerman to workaround this issue you have to run fibratus with `--no-enum-handles` flag. For the long term this should be fixed by querying the object handle in a seperate thread.

Thanks!

**Comment by emmanueltsukerman** [comment]
Thanks. The first command I ran was fibratus run --no-enum-handles, but received an error (see same image).

**Comment by rabbitstack** [comment]
The error is because the compilcation of `multiprocess` module probably failed. Can you confirm there is the multiprocess Cython extension in your site-packages directory? (should be in $PYTHON_HOME\Lib\site-packages\_multiprocess.pyd). Also I see you are using **Anaconda** instead of **CPython**. I didn't test Fibratus on Anaconda.

**Comment by emmanueltsukerman** [comment]
I tried again, installing this time everything through pip. I get the following error:
![fib](https://cloud.githubusercontent.com/assets/23566736/22452812/e7ceb716-e72e-11e6-81ab-322bd0e07a98.png)

**Comment by rabbitstack** [comment]
Please not the following requirements:

- **Python 3.4**
- Visual C++ 2012 or above
- Cython >=0.23.4

You have to run Fibratus under **Python 3.4** (Windows x64).

**Comment by emmanueltsukerman** [comment]
I installed python 3.4, visual C++ 2015 and have Cython 0.23.4. Unfortunately I am getting an error upon "pip install fibratus":
![fib](https://cloud.githubusercontent.com/assets/23566736/22478686/d485e2c6-e79f-11e6-95af-67880f9a23fc.png)

**Comment by rabbitstack** [comment]
1. Make sure to export the `VS100COMNTOOLS` environment variable so it points to `%VS140COMNTOOLS%`.
2. Install Cython. `pip install Cython`

Now, you should run `pip install fibratus` successfully.

**Comment by emmanueltsukerman** [comment]
Looks like the original issue persists with python 3.4:
![fib](https://cloud.githubusercontent.com/assets/23566736/22580638/dffd94a0-e98e-11e6-9254-51c254720b07.png)

**Comment by rabbitstack** [comment]
It's still necessary to include the `--no-enum-handles` flag. The issue needs to be fixed in the code.

**Comment by emmanueltsukerman** [comment]
It looks like 
1. adding _multiprocess.pyd to $PYTHON_HOME\Lib\site-packages\  
and
2. writing the --no-enum-handles flag
fixed the issue. Thanks for the real-time comments.
