### ISSUE TITLE
Filaments crash python

### ISSUE THREAD

**Issue by emmanueltsukerman** [rabbitstack/fibratus#13]
Running filaments causes python to crash:
![crash](https://cloud.githubusercontent.com/assets/23566736/22658990/e4177122-ec50-11e6-81f0-c0677aa8ac5a.png)
![crash2](https://cloud.githubusercontent.com/assets/23566736/22658989/e417683a-ec50-11e6-8474-afa213dc6220.png)

**Comment by rabbitstack** [comment]
@emmanueltsukerman thanks for reporting. I'll try to reproduce/debug during this week.

**Comment by rabbitstack** [comment]
@emmanueltsukerman I was able to reproduce this. It happens when the dictionary containing the kernel event data is pulled from the multiprocessing queue (but the cause is still unknown to me). I will need to dig deeply into it.
