### ISSUE TITLE
CPU load

### ISSUE THREAD

**Issue by emmanueltsukerman** [rabbitstack/fibratus#14]
This is more of a question than a bug report. Is it normal for the CPU load to be relatively high? I am comparing with procmon and it looks higher. Is this expected? Is there a way to reduce the load?

**Comment by rabbitstack** [comment]
Althought I did a huge effort in optimizing the kstream collector so it can operate in a GIL-free manner, there are still room for improvements I need to work. Procmon uses a kernel mode driver to instrument the kernel activity, so it don't have to deal with the parsing logic of the ETW infrastructure. Also it buffers the events in memory before rendering them on the UI.

I recommend using the provided filters facilities. For example, if you're interested in particular kernel events you can run fibratus this way:

`fibratus run --filters CreateProcess LoadImage TerminateThread`. You can also enable per-pid spying.
`fibratus run --pid <pid>`.

The output sink can also make a huge impact on the CPU load. The default console output can produce higher CPU usage, while for example, the Elasticsearch output can lead to better performance.

**Comment by emmanueltsukerman** [comment]
You did do a splendid job in my opinion. I'll keep the tips about the filters and output in mind when running fibratus in the future.
