### ISSUE TITLE
Successfully installed, but can not start

### ISSUE THREAD

**Issue by jialongzhang** [rabbitstack/fibratus#16]
![error](https://cloud.githubusercontent.com/assets/21164042/22770793/0659b08a-ee61-11e6-97e5-f4e11b34707d.jpg)

Successfully installed fibratus-0.6.0

However, when I run it, it shows ImportError: DLL load failed: The specified module could not be found(Last line in figure).

**Comment by rabbitstack** [comment]
Windows XP is not supported. You need to have at least Windows 7.
