### ISSUE TITLE
Logging to elasticsearch errors using standalone installer

### ISSUE THREAD

**Issue by DynaMc** [rabbitstack/fibratus#17]
Hi,

Awesome tool, good work. 

I'm getting the error below while using the standalone installer and attempting to log network connections to elasticsearch. 

The command I used was ```fibratus run --filters Send Recv Connect Disconnect Reconnect```

Looking for suggestions.
Thanks

```
Traceback (most recent call last):
  File "kstream\kstreamc.pyx", line 324, in kstreamc.KEventStreamCollector._proc
ess_kevent (kstream\kstreamc.cpp:3341)
  File "fibratus\entrypoint.py", line 373, in _on_next_kevent
  File "fibratus\entrypoint.py", line 424, in _aggregate
  File "fibratus\output\aggregator.py", line 49, in aggregate
  File "fibratus\output\elasticsearch.py", line 56, in emit
fibratus.errors.InvalidPayloadError: invalid payload for bulk indexing. list exp
ected but <class 'dict'> found
None
Traceback (most recent call last):
  File "kstream\kstreamc.pyx", line 324, in kstreamc.KEventStreamCollector._proc
ess_kevent (kstream\kstreamc.cpp:3341)
  File "fibratus\entrypoint.py", line 373, in _on_next_kevent
  File "fibratus\entrypoint.py", line 424, in _aggregate
  File "fibratus\output\aggregator.py", line 49, in aggregate
  File "fibratus\output\elasticsearch.py", line 56, in emit
fibratus.errors.InvalidPayloadError: invalid payload for bulk indexing. list exp
ected but <class 'dict'> found
None
Traceback (most recent call last):
  File "kstream\kstreamc.pyx", line 324, in kstreamc.KEventStreamCollector._proc
ess_kevent (kstream\kstreamc.cpp:3341)
  File "fibratus\entrypoint.py", line 373, in _on_next_kevent
  File "fibratus\entrypoint.py", line 424, in _aggregate
  File "fibratus\output\aggregator.py", line 49, in aggregate
  File "fibratus\output\elasticsearch.py", line 56, in emit
fibratus.errors.InvalidPayloadError: invalid payload for bulk indexing. list exp
ected but <class 'dict'> found
None

```

**Comment by rabbitstack** [comment]
Bulk indexing is not supported, unless you use a filament and pass a `list` of objects to index. Try to disable it in the configuration file by setting  `bulk: False`. I should set this by default.

**Comment by DynaMc** [comment]
Ahh ok.  

What I'm trying to do here is use it was a forensics  agent. So I was willing to log everything to catch the anomalous connections.  

I was starting with network traffic but did want to include file system after seeing how it worked. 

Passing lists wouldnt be extremely useful since it would make it hard to isolate searches for very specific connections. Eg, show me all connections to 8.8.8.8 and find a timestamp. Then see the file system changes surrounding it as well etc. 

Will need to rethink this approach.

**Comment by rabbitstack** [comment]
Hi @DynaMc 

Bulking is used to do batch indexing on a periodic basis. Real-time aggregation (which can be achieved by setting `bulk` to `False`) can be CPU intensive if there's a lot of events to index, but in your scenario, it would be fine to do it. Just make the configuration change above and run fibratus with network and fs filters.

**Comment by DynaMc** [comment]
I will certainly give it a shot later today and provide some quick feedback for you. I now know what you mean by setting. I was thinking more along the lines of aggregated data (in nested documents). 

Thanks for the quick replies.

**Comment by rabbitstack** [comment]
@DynaMac that would be awesome! Feel free to report any issue or improvement you would like to have in fibratus.

**Comment by DynaMc** [comment]
Okay, well you were right. It works fine. A bit noisy but it's logging to ES ok now.

I have another request though. Maybe the timestamp could be set in the indexing as a date by default, right now it appears to log timestamp as a string. So that a histogram could be used to monitor activity.

**Comment by rabbitstack** [comment]
@DynaMc Thanks for detailed feedback. I'm not sure what do you mean by noisy output. Elasticsearch should be able to infer the timestamp pattern and map the values accordingly. Will need to dig deeper.
Having a dynamic index name could also be helpful.

**Comment by DynaMc** [comment]
By noisy, I just mean a lot of data being logged. For instance I had only networking related items and had nearly 1000 documents after a couple minutes of logging. 

The OS logging is even noisier as you can imagine and as expected. So I was trying to think of a way to help cut down what gets logged, if for instance just polling the kernel every x amount of time. 

Or fore instance, one of the things I was interested in was monitoring dropped ( created ) file and their content. An option to log a known file location would be awesome. 

If I was monitoring​ an infected host, I would be able to see the malware config changes this way without have to physically dig around the OS. 

Just thinking out loud really.

**Comment by rabbitstack** [comment]
@DynaMc, thank you for elaborating that a bit. You can drop/ignore certain kernel events if they are coming from a process whose image name is defined in `skips.images` section of the `fibratus.yml` configuration descriptor. I think that could be easily extrapolated to file names or even ip addresses.
If you create an issue, I could consider shipping those kind of filters in future releases.

For the record, you can also use `--pid` flag to spy on a specific process id. See this [link](http://rabbitstack.github.io/operating%20systems/fibratus-0-4-0/) for more info.

**Comment by DynaMc** [comment]
Thank you for the follow up. Good tips and I think I just need some more playing with the tool to see what I can and cannot do. I'll submit anything I can follow up with.
