### ISSUE TITLE
Any plan to release a core version of fibratus?

### ISSUE THREAD

**Issue by yusufozturk** [rabbitstack/fibratus#175]
Hi Nedim,

I was reading your past commits to understand changes and I heard that more of the new features are coming. We would like to use Fibratus in our project but it's a bit heavy. And I think reason for that is, kevent and kstream are tightly coupled with other packages. An easy mapping:

```
kstream is coupled with "filter", "ps".
kevent is coupled with "kcap".

ps is coupled with "kcap".
kcap is coupled with "filter".

filter is coupled with "alertsender" via actions.
```

filter and kcap are big dependencies. Also queue system from aggregator is moved to kstream and then kevent. I think adding lru cache to the core is also adding extra weight on core.

Do you have any plan to seperate core packages from the main project? Or maybe some decoupling refactoring? Then people can use fibratus-core to get ETW events in a lightest way possible, then people can embed the core an apply their own caching, filtering etc on top of it.

Thanks.

**Comment by rabbitstack** [comment]
Hi @yusufozturk,

Despite the core components are exposed package-wide, Fibratus is not meant to be consumed as a library from third-party software. As a consequence, the internal API may change frequently and inadvertently leading to breaking changes in external clients. If you want to get the events captured by Fibratus into your platform, it is better to rely on output sinks (HTTP, AMQP, Elasticsearch, etc.)

If you still insist in using Fibratus directly from your code, event consumer is not really coupled with the filter engine - SetFilter is engaged in the final caller's, so it is utterly optional. kcap can be completely bypassed by the build flag.

Back to your original question, I'm not planning to work on core component separation as this would result in a significant amount of effort besides defeating Fibratus purpose.

Regards

**Comment by yusufozturk** [comment]
@rabbitstack I understand. I will look into your guidance. Thanks!

**Comment by rabbitstack** [comment]
@yusufozturk feel free to share your use case. If there is a need for a different [output](https://www.fibratus.io/#/outputs/introduction) implementation or wire format e.g. protobuf, we could sort that out.
