### ISSUE TITLE
Elasticsearch indexing - need indices by date

### ISSUE THREAD

**Issue by DynaMc** [rabbitstack/fibratus#19]
Using the exe version the indexing does not use time properly so you cannot get a date histogram. 

- Timestamp should be used correctly 
- That there is an index per day. Should be something like "kernel-%Y.%m.%d"

![image](https://cloud.githubusercontent.com/assets/5316899/24936434/477a8da2-1ef7-11e7-9778-de02404be9b9.png)
![image](https://cloud.githubusercontent.com/assets/5316899/24936443/5f3f38f2-1ef7-11e7-9508-75882d8822dc.png)

No option to use for time-field name. 

We really improve analysis.

**Comment by rabbitstack** [comment]
@DynaMc templated [index names](https://www.fibratus.io/#/outputs/elasticsearch?id=index-name) just landed in [1.0.0](https://github.com/rabbitstack/fibratus/releases/tag/1.0.0).
