### ISSUE TITLE
Error when using registry_persistence_detection filament

### ISSUE THREAD

**Issue by dreadlocked** [rabbitstack/fibratus#20]
When I use the registry_persistence_detection filament, I get the following error message: "ERROR: Fibratus: Unexpected filament error 'DotD' object has no attribute 'key'"

This occurs when I execute a sample of Spora Ranwomware, the program executes, write a registery key but Fibratus throws this error.

**Comment by rabbitstack** [comment]
@dreadlocked thanks for reporting. There is actually an incorrect filter type in the filament (the call to `set_filter('CreateProcess')` should be `set_filter('RegSetValue')`). Could you fix that and try again?

**Comment by dreadlocked** [comment]
Sorry, I can't deal with the "building 'kstreamc' extension  error: Unable to find vcvarsall.bat" pip's error and got no so much time to spend on fixing it. If you can try it by yourself I will appreciate it.

Thanks!

**Comment by rabbitstack** [comment]
You don't have to rebuilt fibratus. Just go to your `$HOME\.fibratus\filaments` directory and modify `registry_persistence_detection.py` with the line I've already mentioned. However, I'll fix that but for the next release.

**Comment by rabbitstack** [comment]
filter has been fixed in the filament
