### ISSUE TITLE
Error DotD object on Filament

### ISSUE THREAD

**Issue by DZKeeper** [rabbitstack/fibratus#21]
Hello,

I am having a hardtime getting it to run in conjunction with an elk stack.

I followed steps in here: https://sematext.com/blog/2016/11/29/fibratus-windows-kernel-logging/

I start using the command : fibratus run --filament elasticsearch_indexing

I am using the windows standalone binary and I get this error constantly:

ERROR: Fibratus: Unexpected filament error 'DotD' object has no attribute 'thread'

I was hopeing to get a steer in the right direction to troubleshoot this.

Thanks

**Comment by rabbitstack** [comment]
Hi @DZKeeper . That filament is no longer required if you want to index the kernel events to Elasticsearch. Just configure the Elasticsearch output in ``fibratus.yml` configuration file and run Fibratus as usual:

`fibratus run`

However, will look deeply into an error and will try to reproduce.

Thanks
