### ISSUE TITLE
Missed UTF-8 codepoints marshalling in writeStringSlowPath?

### ISSUE THREAD

**Issue by mnznndr97** [rabbitstack/fibratus#216]
While parsing some fibratus _http output_, I noticed that in the raw UTF-8 there were some unexpected sequences, for example `0x30` followed by a `0x90`. 

I never used Go, but if I'm understanding correctly, strings are just like a byte array, and no underlying encoding is enforced. 
In `writeStringSlowPath()`, if a byte that needs to be marshalled to json is `> 0x7F`, meaning that in UTF8 it's part of a multi-byte sequence, no extra marshalling is applied and it's written directly to the underlying json stream, which uses UTF-8, creating an "invalid" output if, for example, opened with python.

Is this an expected behavior or should these byte values marshalled in other ways? 

Here an example of a problematic output: [CyberChef - Missed Conversion](https://gchq.github.io/CyberChef/#recipe=From_Hex('Auto')&input=N0IgMjIgNzMgNjUgNzEgMjIgM0EgMzEgMzMgMzIgMzcgMzkgMzAgMkMgMjIgNzAgNjkgNjQgMjIgM0EgMzYgMzcgMzcgMzIgMkMgMjIgNzQgNjkgNjQgMjIgM0EgMzYgMzcgMzcgMzYgMkMgMjIgNjMgNzAgNzUgMjIgM0EgMzAgMkMgMjIgNkUgNjEgNkQgNjUgMjIgM0EgMjIgNTIgNjUgNjcgNTMgNjUgNzQgNTYgNjEgNkMgNzUgNjUgMjIgMkMgMjIgNzQgNzMgMjIgM0EgMjIgMzIgMzAgMzIgMzMgMkQgMzEgMzIgMkQgMzEgMzQgNTQgMzAgMzggM0EgMzMgMzMgM0EgMzUgMzQgMkUgMzAgMzggMzcgMzEgMzEgMzAgMzcgMkIgMzAgMzEgM0EgMzAgMzAgMjIgMkMgMjIgNkIgNzAgNjEgNzIgNjEgNkQgNzMgMjIgM0EgN0IgMjIgNkIgNjUgNzkgNUYgNjggNjEgNkUgNjQgNkMgNjUgMjIgM0EgMjIgNjYgNjYgNjYgNjYgNjMgNjUgMzAgNjQgNjIgMzQgMzAgMzkgMzkgNjUgMzIgMzAgMjIgMkMgMjIgNkIgNjUgNzkgNUYgNkUgNjEgNkQgNjUgMjIgM0EgMjIgNDggNEIgNDUgNTkgNUYgNEMgNEYgNDMgNDEgNEMgNUYgNEQgNDEgNDMgNDggNDkgNEUgNDUgNUMgNUMgNTMgNEYgNDYgNTQgNTcgNDEgNTIgNDUgNUMgNUMgNEQgNjkgNjMgNzIgNkYgNzMgNkYgNjYgNzQgNUMgNUMgNTcgNjkgNkUgNjQgNkYgNzcgNzMgMjAgNEUgNTQgNUMgNUMgNDMgNzUgNzIgNzIgNjUgNkUgNzQgNTYgNjUgNzIgNzMgNjkgNkYgNkUgNUMgNUMgNEUgNkYgNzQgNjkgNjYgNjkgNjMgNjEgNzQgNjkgNkYgNkUgNzMgNUMgNUMgNDQgNjEgNzQgNjEgNUMgNUMgMzQgMzEgMzggNDEgMzAgMzcgMzMgNDEgNDEgMzMgNDIgNDMgMzMgMzQgMzcgMzUgMjIgMkMgMjIgNzMgNzQgNjEgNzQgNzUgNzMgMjIgM0EgMjIgNTMgNzUgNjMgNjMgNjUgNzMgNzMgMjIgMkMgMjIgNzYgNjEgNkMgNzUgNjUgMjIgM0EgMjIgMjAgNUMgNzUgMzAgMzAgMzAgMzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzIgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzEgNjMgMzkgNUMgNzUgMzAgMzAgMzAgNjIgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNkIgNTAgN0UgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgOTAgQTYgQTEgNUMgNzUgMzAgMzAgMzAgMzEgQUQgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQTEgOUYgNUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgREIgQjQgRUYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgN0QgNzUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzEgMzggNjUgNjUgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNkUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzEgMzggN0QgQzcgNUMgNzUgMzAgMzAgMzAgMzAgNDkgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNTYgNzMgN0QgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNkIgNTAgN0UgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgOEEgODMgODUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgOTAgRDUgRDAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgOTggMjkgQjcgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgRTYgQzUgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNEYgODcgNUMgNzUgMzAgMzAgMzEgNjEgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgNjIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgOUYgQzggQ0EgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQTkgNUMgNzUgMzAgMzAgMzEgNjQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgOEEgODMgODUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNjQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgRjcgREEgQUQgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzcgNUMgNzUgMzAgMzAgMzAgMzAgNjUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzEgMzkgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzEgNjMgOTUgNUMgNUMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgNjYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgMjAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNzcgOUIgOTMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgOTAgRDUgRDAgNUMgNzUgMzAgMzAgMzAgMzAgNTUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQTIgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzYgNUMgNzUgMzAgMzAgMzAgMzAgRDAgMkYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgRTYgQzUgMzEgNUMgNzUgMzAgMzAgMzAgMzAgRDYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgRjAgRTAgQjYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzMgNUMgNzUgMzAgMzAgMzAgMzAgNjYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNUMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgMjAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNzcgOUIgOTMgNUMgNzUgMzAgMzAgMzAgMzAgMkYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQTIgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNjcgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQTIgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNjggNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQTIgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNjkgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzQgNUMgNzUgMzAgMzAgMzAgMzcgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNkIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzQgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNzIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzQgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQTIgNUMgNzUgMzAgMzAgMzAgMzUgNUMgNzUgMzAgMzAgMzAgMzYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNzMgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzEgMzkgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgNzcgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzYgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgN0QgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzEgMzkgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgN0YgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgMjAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgODEgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzcgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNjUgQTYgOUUgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzEgNUMgNzUgMzAgMzAgMzAgMzAgOTcgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgNjIgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgNUMgNzUgMzAgMzAgMzAgMzAgQkUgQjMgRUYgNUMgNzUgMzAgMzAgMzAgMzAgMjIgMkMgMjIgNzYgNjEgNkMgNzUgNjUgNUYgNzQgNzkgNzAgNjUgMjIgM0EgMjIgNTIgNDUgNDcgNUYgNDIgNDkgNEUgNDEgNTIgNTkgMjIgN0QgMkMgMjIgNzAgNzMgMjIgM0EgN0IgMjIgNzAgNjkgNjQgMjIgM0EgMzYgMzcgMzcgMzIgMkMgMjIgNzAgNzAgNjkgNjQgMjIgM0EgMzEgMzIgMzAgMzQgMkMgMjIgNkUgNjEgNkQgNjUgMjIgM0EgMjIgNzQgNjEgNzMgNkIgNjggNkYgNzMgNzQgNzcgMkUgNjUgNzggNjUgMjIgMkMgMjIgNjMgNkQgNjQgNkMgNjkgNkUgNjUgMjIgM0EgMjIgNzQgNjEgNzMgNkIgNjggNkYgNzMgNzQgNzcgMkUgNjUgNzggNjUgMjAgNTMgNzkgNkUgNjMgNDYgNzIgNkYgNkQgNDMgNkMgNkYgNzUgNjQgMjIgMkMgMjIgNjUgNzggNjUgMjIgM0EgMjIgNDMgM0EgNUMgNUMgNTcgNjkgNkUgNjQgNkYgNzcgNzMgNUMgNUMgNTMgNzkgNzMgNzQgNjUgNkQgMzMgMzIgNUMgNUMgNzQgNjEgNzMgNkIgNjggNkYgNzMgNzQgNzcgMkUgNjUgNzggNjUgMjIgMkMgMjIgNjMgNzcgNjQgMjIgM0EgNkUgNzUgNkMgNkMgMkMgMjIgNzMgNjkgNjQgMjIgM0EgMjIgNTMgMkQgMzEgMkQgMzUgMkQgMzIgMzEgMkQgMzUgMzggMzYgMzggMzkgMzAgMzggMkQgMzIgMzggMzIgMzUgMzcgMzIgMzAgMzYgMzkgMzUgMkQgMzkgMzMgMzggMzcgMzQgMzYgMzAgMzAgMzggMkQgMzEgMzAgMzAgMzEgMjIgMkMgMjIgNjEgNzIgNjcgNzMgMjIgM0EgNUIgMjIgNzQgNjEgNzMgNkIgNjggNkYgNzMgNzQgNzcgMkUgNjUgNzggNjUgMjIgMkMgMjIgNTMgNzkgNkUgNjMgNDYgNzIgNkYgNkQgNDMgNkMgNkYgNzUgNjQgMjIgNUQgMkMgMjIgNzMgNjUgNzMgNzMgNjkgNkYgNkUgNjkgNjQgMjIgM0EgMzEgMkMgMjIgNzAgNjEgNzIgNjUgNkUgNzQgMjIgM0EgN0IgMjIgNkUgNjEgNkQgNjUgMjIgM0EgMjIgNzMgNzYgNjMgNjggNkYgNzMgNzQgMkUgNjUgNzggNjUgMjIgMkMgMjIgNjMgNkQgNjQgNkMgNjkgNkUgNjUgMjIgM0EgMjIgNDMgM0EgNUMgNUMgNTcgNjkgNkUgNjQgNkYgNzcgNzMgNUMgNUMgNzMgNzkgNzMgNzQgNjUgNkQgMzMgMzIgNUMgNUMgNzMgNzYgNjMgNjggNkYgNzMgNzQgMkUgNjUgNzggNjUgMjAgMkQgNkIgMjAgNkUgNjUgNzQgNzMgNzYgNjMgNzMgMjAgMkQgNzAgMjAgMkQgNzMgMjAgNTMgNjMgNjggNjUgNjQgNzUgNkMgNjUgMjIgMkMgMjIgNjUgNzggNjUgMjIgM0EgMjIgNDMgM0EgNUMgNUMgNTcgNjkgNkUgNjQgNkYgNzcgNzMgNUMgNUMgNzMgNzkgNzMgNzQgNjUgNkQgMzMgMzIgNUMgNUMgNzMgNzYgNjMgNjggNkYgNzMgNzQgMkUgNjUgNzggNjUgMjIgMkMgMjIgNjMgNzcgNjQgMjIgM0EgMjIgNDMgM0EgNUMgNUMgNTcgNjkgNkUgNjQgNkYgNzcgNzMgNUMgNUMgNzMgNzkgNzMgNzQgNjUgNkQgMzMgMzIgNUMgNUMgMjIgMkMgMjIgNzMgNjkgNjQgMjIgM0EgMjIgNTMgMkQgMzEgMkQgMzUgMkQgMzEgMzggMjIgN0QgN0QgN0Q)

**Comment by rabbitstack** [comment]
Hey @mnznndr97 ,

The JSON payload you posted contains the REG_BINARY registry value parameter, which unsurprisingly is a binary blob. Thus, it would require some sort of encoding before transmitting over the wire.

#43 is planning to address this need.
