### ISSUE TITLE
Invalid payload for bulk indexing error

### ISSUE THREAD

**Issue by DZKeeper** [rabbitstack/fibratus#22]
Hi,

I tried running a logsene / fibratus instance following this guide:

https://sematext.com/blog/2016/11/29/fibratus-windows-kernel-logging/

In #21 you mentionned that the filament for elasticsearch_indexing is not needed, so I ran my instance with:

fibratus run 

After configuring the elasticSearch options in the yml file, However, I get this error in the console output. The stream of error is so fast I cannot read all of them, but I took a screenshot of one of them, here:

![error](https://cloud.githubusercontent.com/assets/6238126/25074638/1759f1d2-22ce-11e7-937a-7b4a25c8b2bd.png)

Any help is really appreciated.

Thanks

**Comment by rabbitstack** [comment]
Bulk indexing isn't supported in native mode i.e. when not relying on filament. Try to disable it in the configuration file by setting `bulk: False`.
