### ISSUE TITLE
Spec file not building a working executable

### ISSUE THREAD

**Issue by padcoder** [rabbitstack/fibratus#23]
Hello,

I was able to run pyinstaller using the spec file to generate an executable. However, when I try to run the executable only help and version options are working aprropriately. While I try to use or run with any other options, the execution ends without displayin any ourtput or error to the screen. I also tried building with debug flag, the output is still not helpful. 

Please let me know if you know about the issue or any fix that you can recomment.

Environment: Windows 7, VS 2015, Python 3.4.

**Comment by rabbitstack** [comment]
Hi,

Note when installed from PyPI, `setuptools` descriptor assigns the entrypoint to `cli.main` function. When building the binary with PyInstaller you'll need to explicitly indicate the entrypoint. In `cli.py`, add this snippet to call the `main` function:

```python
if __name__ == '__main__':
     main()
```
Out of curiosity, did you build some additional functionality in fibratus and that's the reason you need to generate the binary?

**Comment by padcoder** [comment]
Thanks for the quick reply. I wanted to modify the default location of
.fibratus folder. After looking into the code I realized that it could be
changed by defining the environment variables. I am trying to play around
the event tracer to understand it's capabilities. Will keep you posted if I
do anything cool.

I might tweak the code to include arguments for filament and config paths.

Thanks again, will try to include main method and see. I think that's the
issue, I should have thought about it.

**Comment by rabbitstack** [comment]
> I wanted to modify the default location of
.fibratus folder. After looking into the code I realized that it could be

Sorry for that. I should point it explicitly in the docs, but at the moment I'm not able to elaborate a decent documentation. You have `FIBRATUS_CONFIG_PATH` env var to change the path of the config descriptor and `FILAMENTS_PATH` for the filaments location.

> I am trying to play around the event tracer to understand it's capabilities. Will keep you posted if I
>do anything cool.
Cool. I would love to see it.

Regards

**Comment by rabbitstack** [comment]
Not applicable anymore. Fibratus now compiles to native binaries.
