### ISSUE TITLE
Is there has any possible way to send alert to a server?

### ISSUE THREAD

**Issue by BaiHLiu** [rabbitstack/fibratus#231]
The way of mail or stack maybe difficult to manage all alert in the center, so is there has any possible way to send alert to a server, such as Elasticsearch or HTTP API?

**Comment by rabbitstack** [comment]
Hey @BaiHLiu ,

As of today, email and Slack are the only supported alert senders, but it should be painless to implement additional alert senders, like HTTP or Elasticsearch. Both of them are on my radar.

**Comment by BaiHLiu** [comment]
Thank you very much for your dedication to this project and to the field of information security!
