### ISSUE TITLE
Can't run with default rules

### ISSUE THREAD

**Issue by BaiHLiu** [rabbitstack/fibratus#233]
I'm sorry to disturb you again😢But I really did get stuck at the `load configuration` step.

When I uncomment the  `filters` section, and set rule path to the default rules folder, it reported an error:
`ERROR msg=unhandled exception when parsing data directory Import, reason: runtime error: slice bounds out of range [xxxx:xxxx]`
I have tried many ways, but it just doesn't work. Is there something I'm overlooking? 

Thank you!

+ OS: Windows2016 R2
+ Fibratus: release 2.0.0
![Snipaste_2023-12-26_20-37-56](https://github.com/rabbitstack/fibratus/assets/31313391/b19a56c1-e0b9-4014-ad24-4b581f28bf68)

**Comment by rabbitstack** [comment]
Hi @BaiHLiu ,

The errors are coming from the third-party PE parser dependency and shouldn't influence the rule loading stage.

You can inspect the log file located and installation root `Logs` directory to confirm rules were loaded correctly. Alternatively, you can run Fibratus with the flag to output logs to the console, e.g.

`fibratus run --logging.log-stdout`

Hope this helps.

**Comment by BaiHLiu** [comment]
Thanks for your attention!!
The log seems like `maximum handle table size reached for 4984 pid. Shrinking table size from 4888 to 800 handles`.

Then I have tried to run in a newly installed virtual mechine( Windows10 X86-64 ), it occured again.

So if the `fibratus` requires specified os verison, or other software environment?
![Snipaste_2023-12-27_09-59-17](https://github.com/rabbitstack/fibratus/assets/31313391/dff9f611-3a1d-456b-9ab3-406fda700060)

**Comment by rabbitstack** [comment]
Are there any rule files in C:\Program Files\Fibratus\Rules directory? Could you attach the full fibratus.log file? At the very beginning of the log file, there should be messages indicating which rules groups are loaded.

Handle table log messages are innocuous and they simply point Fibratus is discarding enumerated process handles as they reached the established limit.

From what I could see by judging your screenshots, the rules seem to be loaded correctly, but let's confirm after you provided the requested information.

FYI, the upcoming Fibratus version will load the rules by default, so no additional config tweaking will be required.

**Comment by BaiHLiu** [comment]
Sure, the rule files is in correct directory.

According to the log file, it looks like the rule has been successfully loaded.

Screenshots for your reference, thanks again!
![Snipaste_2023-12-27_20-58-32](https://github.com/rabbitstack/fibratus/assets/31313391/5eff4c79-1c2c-4bbe-a16d-ada0e65f9e93)
![Snipaste_2023-12-27_21-01-56](https://github.com/rabbitstack/fibratus/assets/31313391/bcd1848d-ddc8-43de-a2c1-acc9a13ca415)

**Comment by rabbitstack** [comment]
Glad you managed to set it up!

**Comment by BaiHLiu** [comment]
Thanks for your help, and if I get a solution I will post an issue again.
