### ISSUE TITLE
`.fibratus\fibratus.yml` not found

### ISSUE THREAD

**Issue by leesei** [rabbitstack/fibratus#25]
I setup fibratus using the installer (v0.7.2).
I get this error when I tried to run:

```
C:\Users\leesei>fibratus run
[2018-07-19 06:58:01.201427] INFO: Fibratus: Starting Fibratus...
[2018-07-19 06:58:01.201427] INFO: Fibratus: Loading configuration from [C:\User
s\leesei\.fibratus\fibratus.yml]
ERROR - C:\Users\leesei\.fibratus\fibratus.yml configuration file does not exist
```

I've to manually create the folder and place `fibratus.yml` for run to execute.
Can the installer create the file during the setup process?

**Comment by rabbitstack** [comment]
Smells like a bug to me. Installer should take care of copying the file to the aforementioned location.

What version of Windows are you running?

**Comment by leesei** [comment]
I'm on Windows 7 Pro.

**Comment by rabbitstack** [comment]
It wasn't reproducible, but shouldn't occur anymore since [1.0.0](https://github.com/rabbitstack/fibratus/releases/tag/1.0.0)
