### ISSUE TITLE
Fibratus halts at "Enumerating system handles..."

### ISSUE THREAD

**Issue by leesei** [rabbitstack/fibratus#26]
I'm on Windows 7 Professional.
I suspected the antivirus but the result is the same.

I'm using administrative cmd btw (is this needed actually?)

**Comment by rabbitstack** [comment]
You can skip system handles enumeration with `fibratus run --no-enum-handles`. While this is just a workaround I have to figure out where I missed accessing synchronous kernel object that's actually the reason why main thread blocks.

**Comment by leesei** [comment]
Thx, I can run with `--no-enum-handles` option.

**Comment by rabbitstack** [comment]
Fixed in [1.0.0](https://github.com/rabbitstack/fibratus/releases/tag/1.0.0).
