### ISSUE TITLE
Store --forward stream to a file

### ISSUE THREAD

**Issue by ablescia** [rabbitstack/fibratus#306]
Which Fibratus configuration should I use to log the events that are typically generated in the console through the **--forward** option?

For instance, I need to store all of the net connections inside a file: `fibratus run --forward kevt.category = "'net'"`.

The stdout redirection is the only way that I found.

Thanks.

**Comment by rabbitstack** [comment]
Hi @ablescia,

You would typically use [captures](https://www.fibratus.io/#/captures/introduction) to persist the event stream. For example:

```
fibratus capture  "kevt.category = 'net'" -o events.kcap 
```

The capture can be replayed with the `replay` command setting up the filter expression if needed.
