### ISSUE TITLE
run fibratus in windows 10 mobile

### ISSUE THREAD

**Issue by XurM00** [rabbitstack/fibratus#46]
Hello friends, for my small project, I would like to run fibratus under windows 10 mobile or windows 8.1 mobile. To my knowledge as it seems, it is not (well till now)  possible to run any custom compiled app in windows 10 mobile. As a test, I cross compiled helloworld.go and tried running in Windows 10 mobile, which didn't work. 

So my question is, is it somehow possible to run fibratus in windows 10 mobile or in windows 8.1 mobile? I have full root storage access in my smartphone, but keep failing to run fibratus.  I have tried to run older version of fibratus which was purely python written. Windows 10 mobile does have limited python3 interpreter but it didnt work as well.

Windows 10 mobile is discontinued and golang mobile supports only android and ios (https://github.com/golang/go/wiki/Mobile).
There are people who compiled golang app for Windows with ARM processor like in surface pro, but they use Windows 10 desktop version. 

I would appreciate for any ideas. 
Thank you

**Comment by rabbitstack** [comment]
`arm64` binaries are on the roadmap. Could you share more details? For example, how did you cross-compile the binary, what are the errors that pop up when you try to run it, etc.?
I'm not very familiar with Windows 10 Mobile. Does it run on both 32/64 bits architectures?

**Comment by XurM00** [comment]
OS: Windows 10 Mobile
Version: 1703
OS Build: 10.0.15063.297
Model: Microsoft Lumia 950 

Error: 
If I "click" on compiled helloword, it asks me "Search for app in the Store? You need to install an app for this task...", same for any python script file. Windows 10 Mobile does not have cmd.exe nor powershell, checked in rooted storage. 


$ cat hello.go
package main

import "fmt"

func main() {
fmt.Println("hello, world")
}

**Comment by rabbitstack** [comment]
To me, this doesn't look like a problem with Go or Python but the requirement Windows Mobile imposes on the packaging format. I assume you can't simply run the binary.

Unfortunately, 32 bits architecture is a no-go for Fibratus. I'm planning on producing the arm64 binaries though.
