### ISSUE TITLE
Consider passing arguments into filament

### ISSUE THREAD

**Issue by TechSupportJosh** [rabbitstack/fibratus#55]
Is it possible to pass variables into a filament from the CLI?

I'd like to be able to pass a process ID into the filament for use in the kfilter(). I tried specifying it at the command line like this:
`fibratus run "ps.name = 'FileZilla.exe' and kevt.category in ('net','file','registry')" -f capture` however this causes all events to be processed. However I can't specify the filter parameters inside the filament's `kfilter()` because I can't see a good way of passing the process ID, short of just processing everything and filtering it out later on.

**Comment by rabbitstack** [comment]
Hi @TechSupportJosh!

That should work fine. Does the filter get apply if you don't provide any filament, like this: `fibratus run "ps.name = 'FileZilla.exe' and kevt.category in ('net','file','registry')"`?

Could you share the `capture` filament or at least the initialization fragment? Regardless of whether this turning out to be a possible bug, I think passing variables to filaments is a good idea that I had at the back of my mind. Probably, one could collect the args via the bulit-in `sys.argv` list.

**Comment by TechSupportJosh** [comment]
I've just tried again and found that it's now only capturing the expected events 😵 Not sure what I did different but appears to be working as expected 👍

**Comment by rabbitstack** [comment]
Glad it's working! I'll leave this issue for considering passing arguments to filaments.
