### ISSUE TITLE
Python Crashes Before it Even Starts

### ISSUE THREAD

**Issue by talliberman** [rabbitstack/fibratus#6]
I'm having trouble compiling fiberatus for my Windows 7 x86 VM.
These are the steps I've tried:

**Downloaded the source files.
Installed Python 2.7.12
Installed Python 3.4.4
Installed visual c++ 2012 express**

**C:\Users\user\Downloads\fibratus-0.1.0>c:\Python27\Scripts\pip install -r requirements.txt**
_Collecting cython==0.23.4 (from -r requirements.txt (line 1))
  Downloading Cython-0.23.4-cp27-none-win32.whl (1.6MB)
    100% |################################| 1.7MB 342kB/s
Collecting docopt==0.6.2 (from -r requirements.txt (line 2))
  Downloading docopt-0.6.2.tar.gz
Collecting ptable==0.9.2 (from -r requirements.txt (line 3))
  Downloading PTable-0.9.2.tar.gz
Collecting logbook==0.12.5 (from -r requirements.txt (line 4))
  Downloading Logbook-0.12.5-cp27-none-win32.whl (84kB)
    100% |################################| 92kB 622kB/s
Collecting apscheduler==3.0.5 (from -r requirements.txt (line 5))
  Downloading APScheduler-3.0.5-py2.py3-none-any.whl (49kB)
    100% |################################| 51kB 721kB/s
Collecting pytest==2.9.1 (from -r requirements.txt (line 7))
  Downloading pytest-2.9.1-py2.py3-none-any.whl (161kB)
    100% |################################| 163kB 562kB/s
Collecting pytest-cov==2.2.1 (from -r requirements.txt (line 8))
  Downloading pytest_cov-2.2.1-py2.py3-none-any.whl
Collecting coveralls==1.1 (from -r requirements.txt (line 9))
  Downloading coveralls-1.1-py2.py3-none-any.whl
Collecting six (from apscheduler==3.0.5->-r requirements.txt (line 5))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting futures (from apscheduler==3.0.5->-r requirements.txt (line 5))
  Downloading futures-3.0.5-py2-none-any.whl
Collecting pytz (from apscheduler==3.0.5->-r requirements.txt (line 5))
  Downloading pytz-2016.4-py2.py3-none-any.whl (480kB)
    100% |################################| 481kB 371kB/s
Collecting tzlocal (from apscheduler==3.0.5->-r requirements.txt (line 5))
  Downloading tzlocal-1.2.2.tar.gz
Collecting py>=1.4.29 (from pytest==2.9.1->-r requirements.txt (line 7))
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |################################| 92kB 737kB/s
Collecting colorama (from pytest==2.9.1->-r requirements.txt (line 7))
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting coverage>=3.7.1 (from pytest-cov==2.2.1->-r requirements.txt (line 8)
)
  Downloading coverage-4.1-cp27-cp27m-win32.whl (164kB)
    100% |################################| 174kB 197kB/s
Collecting requests>=1.0.0 (from coveralls==1.1->-r requirements.txt (line 9))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |################################| 512kB 494kB/s
Installing collected packages: cython, docopt, ptable, logbook, six, futures, py
tz, tzlocal, apscheduler, py, colorama, pytest, coverage, pytest-cov, requests,
coveralls
  Running setup.py install for docopt ... done
  Running setup.py install for ptable ... done
  Running setup.py install for tzlocal ... done
Successfully installed apscheduler-3.0.5 colorama-0.3.7 coverage-4.1 coveralls-1
.1 cython-0.23.4 docopt-0.6.2 futures-3.0.5 logbook-0.12.5 ptable-0.9.2 py-1.4.3
1 pytest-2.9.1 pytest-cov-2.2.1 pytz-2016.4 requests-2.10.0 six-1.10.0 tzlocal-1
.2.2
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and._

**C:\Users\user\Downloads\fibratus-0.1.0>c:\Python34\Scripts\pip install -r requirements.txt**
_Collecting cython==0.23.4 (from -r requirements.txt (line 1))
  Downloading Cython-0.23.4-cp34-none-win32.whl (1.6MB)
    100% |################################| 1.7MB 201kB/s
Collecting docopt==0.6.2 (from -r requirements.txt (line 2))
  Using cached docopt-0.6.2.tar.gz
Collecting ptable==0.9.2 (from -r requirements.txt (line 3))
  Using cached PTable-0.9.2.tar.gz
Collecting logbook==0.12.5 (from -r requirements.txt (line 4))
  Downloading Logbook-0.12.5-cp34-none-win32.whl (85kB)
    100% |################################| 86kB ...
Collecting apscheduler==3.0.5 (from -r requirements.txt (line 5))
  Using cached APScheduler-3.0.5-py2.py3-none-any.whl
Collecting pytest==2.9.1 (from -r requirements.txt (line 6))
  Using cached pytest-2.9.1-py2.py3-none-any.whl
Collecting pytest-cov==2.2.1 (from -r requirements.txt (line 7))
  Using cached pytest_cov-2.2.1-py2.py3-none-any.whl
Collecting coveralls==1.1 (from -r requirements.txt (line 8))
  Using cached coveralls-1.1-py2.py3-none-any.whl
Collecting tzlocal (from apscheduler==3.0.5->-r requirements.txt (line 5))
  Using cached tzlocal-1.2.2.tar.gz
Collecting pytz (from apscheduler==3.0.5->-r requirements.txt (line 5))
  Using cached pytz-2016.4-py2.py3-none-any.whl
Collecting six (from apscheduler==3.0.5->-r requirements.txt (line 5))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest==2.9.1->-r requirements.txt (line 6))
  Using cached py-1.4.31-py2.py3-none-any.whl
Collecting colorama (from pytest==2.9.1->-r requirements.txt (line 6))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting coverage>=3.7.1 (from pytest-cov==2.2.1->-r requirements.txt (line 7)
)
  Downloading coverage-4.1.tar.gz (370kB)
    100% |################################| 372kB 375kB/s
Collecting requests>=1.0.0 (from coveralls==1.1->-r requirements.txt (line 8))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Installing collected packages: cython, docopt, ptable, logbook, pytz, tzlocal, s
ix, apscheduler, py, colorama, pytest, coverage, pytest-cov, requests, coveralls

  Running setup.py install for docopt
  Running setup.py install for ptable
  Running setup.py install for tzlocal
  Running setup.py install for coverage
Successfully installed apscheduler-3.0.5 colorama-0.3.7 coverage-4.1 coveralls-1
.1 cython-0.23.4 docopt-0.6.2 logbook-0.12.5 ptable-0.9.2 py-1.4.31 pytest-2.9.1
 pytest-cov-2.2.1 pytz-2016.4 requests-2.10.0 six-1.10.0 tzlocal-1.2.2
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and._

**C:\Users\user\Downloads\fibratus-0.1.0\fibratus>c:\Python27\Scripts\pip.exe install nuitka**
_Collecting nuitka
  Downloading Nuitka-0.5.20.tar.gz (1.5MB)
    100% |################################| 1.5MB 252kB/s
Installing collected packages: nuitka
  Running setup.py install for nuitka ... done
Successfully installed nuitka-0.5.20_

**C:\Users\user\Downloads\fibratus-0.1.0\fibratus>c:\Python34\Scripts\pip.exe install nuitka**
_Collecting nuitka
  Using cached Nuitka-0.5.20.tar.gz
Installing collected packages: nuitka
  Running setup.py install for nuitka
Successfully installed nuitka-0.5.20
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and._

**c:\Python27\scripts\nuitka --recurse-all --standalone --output-dir=build --verbose cli.py**
_The build was successful but the binary was in build/cli.dist.
Renamed it to fibratus.exe, and ran it, this was the output:
Traceback (most recent call last):
  File "C:\Users\user\Downloads\fibratus-0.1.0\cli.py", line 35, in <module>
  File "C:\Users\user\Downloads\fibratus-0.1.0\fibratus\apidefs\sys.py", line 18,
 in <module>
    from ctypes.wintypes import DWORD, ULONG, PULONG, USHORT, HANDLE, BOOL, SHOR
T, WCHAR, CHAR, WORD, LPDWORD
ImportError: cannot import name PULONG_

**So I figured I was compiling with the wrong python version.**

**Then I compiled with Python34**
**C:\Users\user\Downloads\fibratus-0.1.0>c:\python34\scripts\nuitka --recurse-all -
-standalone --output-dir=build --verbose cli.py**

**And it compiled successfuly**
**C:\Users\user\Downloads\fibratus-0.1.0>c:\Python27\python setup.py build_ext --inplace**
_running build_ext
skipping 'kstream\kstreamc.c' Cython extension (up-to-date)
building 'kstreamc' extension
creating build
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\kstream
C:\Program Files\Microsoft Visual Studio 11.0\VC\BIN\cl.exe /c /nologo /Ox /MD /
W3 /GS- /DNDEBUG -Ic:\Python27\include -Ic:\Python27\PC /Tckstream\kstreamc.c /F
obuild\temp.win32-2.7\Release\kstream\kstreamc.obj
kstreamc.c
kstream\kstreamc.c(2299) : warning C4229: anachronism used : modifiers on data a
re ignored
kstream\kstreamc.c(2570) : warning C4018: '<' : signed/unsigned mismatch
kstream\kstreamc.c(2666) : warning C4133: 'function' : incompatible types - from
 'LPTSTR' to 'const Py_UNICODE *'
kstream\kstreamc.c(3497) : warning C4133: 'function' : incompatible types - from
 'LPTSTR' to 'const Py_UNICODE *'
kstream\kstreamc.c(5001) : warning C4133: 'function' : incompatible types - from
 'wchar_t [256]' to 'LPSTR'
C:\Program Files\Microsoft Visual Studio 11.0\VC\BIN\link.exe /DLL /nologo /INCR
EMENTAL:NO /LIBPATH:c:\Python27\libs /LIBPATH:c:\Python27\PCbuild /LIBPATH:c:\Py
thon27\PC\VS9.0 tdh.lib advapi32.lib ole32.lib /EXPORT:initkstreamc build\temp.w
in32-2.7\Release\kstream\kstreamc.obj /OUT:C:\Users\user\Downloads\fibratus-0.1.0
\kstreamc.pyd /IMPLIB:build\temp.win32-2.7\Release\kstream\kstreamc.lib /MANIFES
TFILE:build\temp.win32-2.7\Release\kstream\kstreamc.pyd.manifest
   Creating library build\temp.win32-2.7\Release\kstream\kstreamc.lib and object
 build\temp.win32-2.7\Release\kstream\kstreamc.exp_

**Then I tried to run the version that was compiled with python34 and this was the output**
**C:\Users\user\Downloads\fibratus-0.1.0>C:\Users\user\Downloads\fibratus-.1.0\fibratus\build\cli.dist\fibratus.exe**
_Traceback (most recent call last):
  File "C:\Users\user\Downloads\fibratus-0.1.0\fibratus\build\cli.dist\cli.py", l
ine 40, in <module>
  File "C:\Users\user\Downloads\fibratus-0.1.0\fibratus\fibratus_entrypoint.py",
line 17, in <module>
    from kstreamc import KEventStreamCollector
ImportError: Module use of python27.dll conflicts with this version of Python._

**So I recompiled kstreamc with Python34:**

**C:\Users\user\Downloads\fibratus-0.1.0>c:\Python34\python setup.py build_ext --inplace**
_running build_ext
skipping 'kstream\kstreamc.c' Cython extension (up-to-date)
building 'kstreamc' extension
creating build\temp.win32-3.4
creating build\temp.win32-3.4\Release
creating build\temp.win32-3.4\Release\kstream
C:\Program Files\Microsoft Visual Studio 11.0\VC\BIN\cl.exe /c /nologo /Ox /MD /
W3 /GS- /DNDEBUG -Ic:\Python34\include -Ic:\Python34\include /Tckstream\kstreamc
.c /Fobuild\temp.win32-3.4\Release\kstream\kstreamc.obj
kstreamc.c
kstream\kstreamc.c(2299) : warning C4229: anachronism used : modifiers on data a
re ignored
kstream\kstreamc.c(2570) : warning C4018: '<' : signed/unsigned mismatch
kstream\kstreamc.c(2666) : warning C4133: 'function' : incompatible types - from
 'LPTSTR' to 'const Py_UNICODE *'
kstream\kstreamc.c(3497) : warning C4133: 'function' : incompatible types - from
 'LPTSTR' to 'const Py_UNICODE *'
kstream\kstreamc.c(5001) : warning C4133: 'function' : incompatible types - from
 'wchar_t [256]' to 'LPSTR'
C:\Program Files\Microsoft Visual Studio 11.0\VC\BIN\link.exe /DLL /nologo /INCR
EMENTAL:NO /LIBPATH:c:\Python34\libs /LIBPATH:c:\Python34\PCbuild tdh.lib advapi
32.lib ole32.lib /EXPORT:PyInit_kstreamc build\temp.win32-3.4\Release\kstream\ks
treamc.obj /OUT:C:\Users\user\Downloads\fibratus-0.1.0\kstreamc.pyd /IMPLIB:build
\temp.win32-3.4\Release\kstream\kstreamc.lib /MANIFESTFILE:build\temp.win32-3.4\
Release\kstream\kstreamc.pyd.manifest
   Creating library build\temp.win32-3.4\Release\kstream\kstreamc.lib and object
 build\temp.win32-3.4\Release\kstream\kstreamc.exp_

**Finally it looked like something was working:**
**C:\Users\user\Downloads\fibratus-0.1.0>C:\Users\user\Downloads\fibratus-0.1.0\fibratus\build\cli.dist\fibratus.exe**
_Usage:
    fibratus run ([--filament=<filament>] | [--filters <kevents>...])
    fibratus list-kevents
    fibratus list-filaments
    fibratus -h | --help
    fibratus --version_

**Then I got this because of UAC, which looked promising:**
**C:\Users\user\Downloads\fibratus-0.1.0>C:\Users\user\Downloads\fibratus-0.1.0\fibratus\build\cli.dist\fibratus.exe run**
_ERROR - You don't have administrative privileges. Stopping fibratus...
Stopping fibratus..._

**So I ran it again with an elevated command_prompt:**

**At first the output was "starting fiberatus...", then "Done", and then a fibratus.exe crashed.**
**The crash:**
_Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	fibratus.exe
  Application Version:	0.0.0.0
  Application Timestamp:	577ce020
  Fault Module Name:	kstreamc.pyd
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	577ce1ca
  Exception Code:	c0000005
  Exception Offset:	00002bc8
  OS Version:	6.1.7601.2.1.0.256.28
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789_

**Can you please help me out?**

**Comment by rabbitstack** [comment]
Did you try running Fibratus directly from byte code? `python cli.py run`. Does the same error occur?

**Comment by talliberman** [comment]
I did, and yes it does.

**Comment by rabbitstack** [comment]
Remove all `kstreamc` Cython extensions. Compile the new extension (make sure it's compiled against python3.3) and place it inside `site-packages` directory. Let me know if that works.

**Comment by jjjan** [comment]
i face this issue now. so any solution ?
