### ISSUE TITLE
how can i make it run?

### ISSUE THREAD

**Issue by jjjan** [rabbitstack/fibratus#7]
Hello after a lot's of afford it's not running and i am exhausted. i have some question that you may help me.
1- is it possible run at windows 2008 or 2012?
2- portable version not working in windows 8.1 and i have lot's of error so what should i do?
3- should i turn off windows or any related security product?
4- pip installing not working hear is error 
[`screenshot`](https://i.imgsafe.org/274576c29c.png)
5- Does we need to change windows env like use test mode?
6- can you make a program as service?

please make video tutorial to install it. or publish virtual machine that the program is installed at.

**Comment by rabbitstack** [comment]
Please note Fibratus requires Python **3.4** in order to run correctly. The binary distribution is going to be discontinued (read more [here](http://rabbitstack.github.io/operating%20systems/fibratus-0-2-3/l)). Shipping Fibratus as Windows service is on the roadmap.

**Comment by jjjan** [comment]
after lot's of hard work i facing with this error 
λ fibratus run
Traceback (most recent call last):
  File "C:\Python34\Scripts\fibratus-script.py", line 11, in <module>
    load_entry_point('fibratus==0.2.3', 'console_scripts', 'fibratus')()
  File "C:\Python34\lib\site-packages\fibratus\cli.py", line 90, in main
    fibratus = Fibratus(filament, enum_handles=enum_handles)
  File "C:\Python34\lib\site-packages\fibratus\fibratus_entrypoint.py", line 85, in __init__
    self.keventq = Queue()
  File "C:\Python34\lib\site-packages\multiprocess\context.py", line 100, in Queue
    from .queues import Queue
  File "C:\Python34\lib\site-packages\multiprocess\queues.py", line 22, in <module>
    import _multiprocess as _multiprocessing
ImportError: No module named '_multiprocess'

**Comment by rabbitstack** [comment]
Can you post the output of the `pip list` command?

**Comment by jjjan** [comment]
λ pip list
anyconfig (0.6.0)
APScheduler (3.0.5)
Cython (0.23.4)
dill (0.2.5)
docopt (0.6.2)
fibratus (0.2.3)
Logbook (0.12.5)
multiprocess (0.70.4)
pika (0.10.0)
pip (8.1.2)
PTable (0.9.2)
pyaml (15.8.2)
pyreadline (2.1)
pytz (2016.6.1)
PyYAML (3.12)
setuptools (27.3.0)
six (1.10.0)
tzlocal (1.2.2)

**Comment by rabbitstack** [comment]
You will need a C++ compiler installed to compile the **Cython** extensions of the `multiprocess` module as well the kernel event stream collector. See this issue for the multiprocess module.

https://github.com/uqfoundation/multiprocess/issues/10

**Comment by jjjan** [comment]
ok multiprocess is fixed but other errors comes up
λ fibratus
Traceback (most recent call last):
  File "C:\Python27\Scripts\fibratus-script.py", line 11, in <module>
    load_entry_point('fibratus==0.2.3', 'console_scripts', 'fibratus')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2598, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2258, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\fibratus\cli.py", line 35, in <module>
    from fibratus.apidefs.sys import set_console_ctrl_handler, PHANDLER_ROUTINE
  File "c:\python27\lib\site-packages\fibratus\apidefs\sys.py", line 18, in <module>
    from ctypes.wintypes import DWORD, ULONG, PULONG, USHORT, HANDLE, BOOL, SHORT, WCHAR, CHAR, WORD, LPDWORD
ImportError: cannot import name PULONG

**Comment by rabbitstack** [comment]
It's pretty straightforward:

1. Download and install the Python 3.4 distribution.
2. Download Visual Studio and install Visual C++. Make sure to export the `VS100COMNTOOLS` so it points to `%VS140COMNTOOLS%`.
3. Install Cython. `pip install Cython`
4. Finally, install Fibratus. `pip install fibratus`

**Comment by jjjan** [comment]
not working again the step i do
1- download python 3.4
2- install visual c++ 10 as fibratus need and do this step as mentioned for multiprocess
    # installed Visual Studio Community 2015 RC
# installed Python Tools 2.2 RC for Visual Studio 2015
# installed Microsoft Visual C++ Compiler for Python 2.7
# installed Miniconda 3.10.1 (64-bit) for Python 2.7
# installed Git for Windows 1.9.5-preview20150319 (including cmd tools)
>$ conda install pip
>$ conda install setuptools
>$ pip install git+https://github.com/uqfoundation/pathos.git@master

3- I Export the VS100COMNTOOLS environment variable so it points to %VS140COMNTOOLS%
%VS140COMNTOOLS% is for visual studio 2014!!!!! you mentioned about it i have it too
4- pip install Cython
5- pip install fibratus

and this error rise again
Traceback (most recent call last):
File "C:\Python34\Scripts\fibratus-script.py", line 11, in 
load_entry_point('fibratus==0.2.3', 'console_scripts', 'fibratus')()
File "C:\Python34\lib\site-packages\fibratus\cli.py", line 90, in main
fibratus = Fibratus(filament, enum_handles=enum_handles)
File "C:\Python34\lib\site-packages\fibratus\fibratus_entrypoint.py", line 85, in init
self.keventq = Queue()
File "C:\Python34\lib\site-packages\multiprocess\context.py", line 100, in Queue
from .queues import Queue
File "C:\Python34\lib\site-packages\multiprocess\queues.py", line 22, in 
import _multiprocess as _multiprocessing
ImportError: No module named '_multiprocess'

so could you explain me how to solve the problem or at least install fibratus as you mentioned on new windows 7  x86 and see the result. or publish the vm.

**Comment by rabbitstack** [comment]
It might be an issue with your Visual Studio installation. `pip` is failing to invoke the compiler so the `multiprocess` module fallbacks to the standard multiprocessing facility. What's the output of `pip install multiprocess`?

**Comment by jjjan** [comment]
λ pip install multiprocess
You are using pip version 6.0.8, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): multiprocess in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): dill>=0.2.5 in c:\python34\lib\site-packages (from multiprocess)
Requirement already satisfied (use --upgrade to upgrade): pyreadline>=1.7.1 in c:\python34\lib\site-packages (from dill>=0.2.5->multiprocess)

**Comment by rabbitstack** [comment]
can you confirm there is the multiprocess extension in your `site-packages` directory? (`%PYTHON_HOME%\Lib\site-packages\_multiprocess.pyd`)

**Comment by jjjan** [comment]
there isn't any _multiprocess.pyd file. so what should i do now?

**Comment by rabbitstack** [comment]
Which version of Windows are you running?

**Comment by jjjan** [comment]
windows 7 x86 .what is the best windows version to run fibratus?

**Comment by rabbitstack** [comment]
Fibratus had been tested on Windows 7, 8 and 10. I didn't have an opportunity to test it on server versions, but it should be agnostic regarding the Windows version (as long as the basic ETW API support is present).

**Comment by jjjan** [comment]
ok thanks but the problem is exist and Python Crashes. any solutions?

**Comment by rabbitstack** [comment]
Now you've correctly configured the C compiler, I would try a fresh install of Fibratus, in a new virtual env or uninstalling the Python itself.

**Comment by jjjan** [comment]
thanks please share the result here as soon as possible.

**Comment by jjjan** [comment]
do you fresh install of Fibratus? can you share the vm?

**Comment by rabbitstack** [comment]
I think there has been a misunderstanding. It was meant for you to try a fresh install of Fibratus, i.e. uninstalling your Python 3.4 distribution, and then following the installation instructions on Fibratus.
I don't think sharing a Windows VM would be legal at all.

**Comment by jjjan** [comment]
Ok i do that and Python Crashes again.  so what is your idea forget to run the project or you have solution for that? my be you need to install it on fresh machine and share what happens.

**Comment by dpicollege** [comment]
I have same issue  python crashes on windows 7.

**Comment by rabbitstack** [comment]
@jjjan @dpicollege If I have some time, I'll try it this week on a pristine Windows VM.

**Comment by rabbitstack** [comment]
I just tried the latest Fibratus version on a Windows 7 VM (Python3.4 and Visual C++ 2015 installed), and it works as expected. You are starting Fibratus with admin's user permissions?

**Comment by jjjan** [comment]
yeap i do that. so what exactly install please share the link of python and visual c++ 2015 or what ever that need to install.
and please make movie of installation to see what exactly do. thanks

**Comment by rabbitstack** [comment]
As I already stated, the installation process is pretty straightforward. 

- Python [download](https://www.python.org/downloads/release/python-344/)
- Visual Studio Community [download](https://www.visualstudio.com/downloads/)

Can you check if there's `fibratus.log` file in your `%PYTHON_HOME%\Lib\site-packages` directory?

**Comment by jjjan** [comment]
i don't have this file. may i please you to install it on my windows 7.
so could you send me your email and then i send my windows 7 credentials to install fibratus.
thanks

**Comment by dpicollege** [comment]
good suggestion @jjjan  idea make video how to install them.

1-install windows 8.1
2- install Python 3.4
3- install cython
4- install Visual Studio Community 
4-pip install fibrates . errors comes up "Unable to find vcvarsall.bat" after a lot's of search I find out I should install windows Download Windows 8.1 SDK is it correct?
do you also see this problem?

and at least fibratus installation is stop.

**Comment by rabbitstack** [comment]
@jjan, the kernel stream collector creates that log file when it boots. Maybe it don't have enough privileges to write to that directory, and the Python interpreter crashes. My mail is bhnedo@hotmail.com.

@dpicollege there is no need to install the Windows SDK. Just make sure to export the VS100COMNTOOLS environment variable so it points to %VS140COMNTOOLS%.

**Comment by dpicollege** [comment]
after install Visual Studio Community  I and export  VS100COMNTOOLS environment variable to %VS140COMNTOOLS% I face this error 

cythoning kstream/kstreamc.pyx to kstream\kstreamc.c

building 'kstreamc' extension

error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK
 7.1": www.microsoft.com/download/details.aspx?id=8279

should I install  Microsoft Visual C++ 10.0?

**Comment by rabbitstack** [comment]
Visual Studio should have install the Visual C++ compiler (if you have checked it under Languages section).

**Comment by jjjan** [comment]
thanks slove
